### ISSUE TITLE
resetting font size

### ISSUE THREAD

**Issue by mweinelt** [andir/ate#16]
We can currently zoom in and zoom out, but not reset to the initial font size when we started. The common keybind for this would probably be `CTRL+0`.

**Comment by andir** [comment]
Probably makes sens.. first we should talk about actually setting a default font size. So far I left all that to VTE/GTK as I do not want to get into the font size/scaling business. Those 4k screen users would probably shout at me for picking something that doesn't suite their eyes :/

**Comment by mweinelt** [comment]
How about copying the default pango font description at startup and resetting to that? That would still leave the default elsewhere.
