### ISSUE TITLE
ATE freezes when using link picker without firefox opened

### ISSUE THREAD

**Issue by tklitschi** [andir/ate#21]
When Using the link Picker (Crtl+Alt+U in example Config) it executing firefox with the link. When having no Firefox Session opened, the terminal freezes and becomes unusable, until you close the Firefox Session and start a new one not via the Picker. 

*Steps to reproduce*
- Close all Firefox Session
- Launch ATE and and execute 'echo "https://nixos.org"
- press ctrl+alt+u and select nixos.org

This becomes completly annouying when not using firefox as main Browser. You have to copy the link from the Browser and open it in your default Browser or launch a new firefox instance to use ATE again. 
So it also would be nice to use the xdg-settings 'default-web-browser' instead of firefox.

**Comment by andir** [comment]
Use the latest version. It does fork before spawning the new process.

**Comment by tklitschi** [comment]
my fault. 
fixed.
